#import "gov_lib.typ": *

#let d = json("results.json")
#let scope = d.scope
#let base = d.baseline
#let plan = d.plan
#let curve = d.curve

#let titlecase(str_) = str_.split(" ").map(w =>
  if w.len() > 3 or w == w.trim(regex("[a-z]")) { upper(w.slice(0, 1)) + w.slice(1) } else { w }
).join(" ")
#let doctitle = titlecase(scope.domain_title) + " Assessment: " + scope.adm2 + " District"

#let months = ("January", "February", "March", "April", "May", "June", "July",
               "August", "September", "October", "November", "December")
#let issued = months.at(int(d.run.generated_at.slice(5, 7)) - 1) + " " + d.run.generated_at.slice(0, 4)

#set document(title: doctitle, author: "Open Siting Agent")

// ============================================================ page setup
#set page(
  paper: "a4",
  margin: (top: 24mm, bottom: 22mm, x: 24mm),
  footer: context {
    if counter(page).get().first() > 1 {
      align(center)[
        #text(font: sans, size: 8.5pt, fill: navy)[#doctitle]
        #linebreak()
        #text(font: sans, size: 9pt)[#counter(page).display()]
      ]
    }
  },
)

#set text(font: sans, size: 10.5pt, fill: ink, lang: "en")
#set par(justify: false, leading: 0.72em, spacing: 1.0em)
#show link: set text(fill: navy)
#set table(stroke: none)
#show raw: set text(font: ("Consolas", "DejaVu Sans Mono"), size: 8pt)

#show figure.where(kind: table): set figure(placement: none)
#show figure.where(kind: table): set figure.caption(position: top)
#show figure.where(kind: image): set figure.caption(position: bottom)
#show figure.caption: it => block(width: 100%)[
  #align(center)[#text(font: sans-bold, size: 8.5pt, weight: 700)[
    #it.supplement #context it.counter.display(it.numbering). #it.body
  ]]
]
#set figure(numbering: "1")

#set heading(numbering: none)
#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  v(6pt)
  text(font: sans-bold, size: 21pt, weight: 700, fill: navy)[#smallcaps(it.body)]
  v(8pt)
}
#show heading.where(level: 2): it => {
  v(10pt)
  text(font: sans-bold, size: 14pt, weight: 700, fill: navy)[#it.body]
  v(3pt)
}
#show heading.where(level: 3): it => {
  v(7pt)
  text(font: sans-bold, size: 11pt, weight: 700, fill: ink)[#it.body]
  v(2pt)
}

// ============================================================ cover
#set page(margin: 0pt, footer: none)

#grid(
  rows: (53%, 47%),
  columns: (100%),
  gutter: 0pt,
  block(width: 100%, height: 100%, clip: true)[
    #image("map_situation.png", width: 100%, height: 100%, fit: "cover")
  ],
  block(width: 100%, height: 100%, fill: band, inset: (x: 26mm, y: 18mm))[
    #set par(spacing: 0pt, leading: 0.42em)
    #text(font: ("Georgia", "Libertinus Serif"), size: 29pt, fill: white)[#doctitle]
    #v(10pt)
    #text(font: ("Georgia", "Libertinus Serif"), size: 13pt, fill: white, style: "italic")[
      #scope.country #sym.dot.c #issued
    ]
    #v(1fr)
    #text(font: sans-bold, size: 15pt, weight: 700, fill: white.darken(12%))[
      OPEN SITING AGENT
    ]
    #v(4pt)
    #text(font: sans, size: 8.5pt, fill: white.darken(22%))[
      An open-source geospatial analysis tool. Not a publication of any
      government or agency.
    ]
  ],
)

#pagebreak()
#set page(
  margin: (top: 24mm, bottom: 22mm, x: 24mm),
  footer: context {
    if counter(page).get().first() > 1 {
      align(center)[
        #text(font: sans, size: 8.5pt, fill: navy)[#doctitle]
        #linebreak()
        #text(font: sans, size: 9pt)[#counter(page).display()]
      ]
    }
  },
)
#counter(page).update(1)

// ============================================================ doc control
#align(center)[#text(font: sans, size: 10.5pt, fill: navy)[#doctitle]]
#v(24pt)

#text(font: sans-bold, size: 14pt, weight: 700, fill: navy)[Document Control]
#v(6pt)

#table(
  columns: (34%, 1fr),
  stroke: 0.5pt + hair,
  inset: (x: 7pt, y: 6pt),
  fill: (x, y) => if calc.even(y) { shade } else { white },
  ..(
    ("Assessment", doctitle),
    ("Jurisdiction", scope.adm2 + " District, " + scope.country + " (" + scope.iso3 + ")"),
    ("Subject", "Placement of " + str(scope.budget) + " additional " + scope.unit
       + (if scope.budget > 1 { "s" } else { "" }) + " under a fixed budget"),
    ("Issued", d.run.generated_at),
    ("Run identifier", d.run.id),
    ("Provenance hash", d.run.provenance_hash),
    ("Prepared by", "An autonomous analysis agent operating on open data"),
    ("Reviewed by", if d.audit.len() > 0 { d.audit.at(0).actor + " (see Chapter 5)" } else { "Not reviewed" }),
    ("Supersession", "This assessment supersedes no prior issue. Each run is issued "
       + "under its own identifier and no run is revised in place."),
    ("Maintenance", "Regenerated by replaying the manifest recorded in Appendix C. "
       + "Any change to a source query, a cleaning rule or a retrieval date "
       + "changes the provenance hash."),
  ).map(r => (
    text(font: sans-bold, size: 9pt, weight: 700)[#r.at(0)],
    text(font: sans, size: 9pt)[#r.at(1)],
  )).flatten()
)

#v(14pt)
#callout("Status of this Assessment")[
  This assessment is advisory. It was produced from published open data without
  field verification. Land availability, tenure, water table, community consent
  and construction feasibility are outside the data used here and remain matters
  for the reviewing officer. Recommendations in Chapter 4 should be read together
  with the limitations at Section 1.4 and the data anomalies at Appendix A.
]

#pagebreak()

#outline(title: [Table of Contents], depth: 2, indent: 1.2em)
#v(10pt)
#outline(title: [List of Figures], target: figure.where(kind: image))
#v(6pt)
#outline(title: [List of Tables], target: figure.where(kind: table))

// ============================================================ ch 1
= Chapter 1: Introduction

Chapter 1 states the purpose of this assessment, how it should be read, what it
covers, and the limits within which its findings hold. It closes with the data
sources on which every figure in the assessment rests.

== Purpose

This assessment identifies where #str(scope.budget) additional
#scope.unit#if scope.budget > 1 [s] should be placed in #scope.adm2 District so
as to bring the largest number of people currently without service inside a
#scope.unit service radius, and states what each of those placements would
achieve.

== How to Read this Assessment

Chapter 2 describes the current state of service in the district. Chapter 3
states how the assessment was carried out, including every retrieval made and
every cleaning rule applied. Chapter 4 gives the recommendation. Chapter 5
records the review, including each point at which a reviewing officer overruled
the analysis and what that decision cost. Chapter 6 tests how far the
recommendation depends on assumptions that can reasonably be changed.

Appendix A records properties of the source data that would have changed a
figure had they been read differently. Appendix B is the retrieval record.
Appendix C is the reproduction record.

== Scope and Applicability

This assessment covers #scope.adm2 District only. Coverage is computed against
#scope.unit records held in the source register; infrastructure that is not
recorded appears here as absence of service. The method is not specific to this
district or this domain, and the same procedure applies without modification to
health facility access, disease control and environmental monitoring.

== Limitations

+ *The register is not a census.* Coverage is computed against recorded
  #scope.unit#if scope.budget > 1 [s] only. Unmapped infrastructure appears as
  absence of service.
+ *Records age.* The median record for this district is
  #str(scope.median_record_age_years) years old. Findings describe the surveyed
  state of the network, not necessarily its state today.
+ *Distance is straight-line.* Terrain, watercourses and footpath networks are
  not modelled, so real walking distances exceed the radius used here.
+ *Costs are not modelled.* Rehabilitating an existing point and constructing a
  new one draw equally on the budget. Chapter 6 reports what changes when only
  rehabilitation is permitted.
+ *No field verification was performed.* No site in Chapter 4 has been visited.

== Decisions This Assessment Rests On

#let auth = d.at("authorship", default: (:))
#let decs = d.at("decisions", default: ())

Certain judgements cannot be derived from data: what distance counts as served,
whose need a fixed programme answers, and whether a register of a given age is
fit to direct capital spending. Each is recorded below with the name of whoever
took it and the reason they gave. The analysis refuses to run without them
rather than assuming one.

#if decs.len() > 0 [
  #figure(
    gov-tbl(
      columns: (auto, auto, auto, 1fr),
      align: (left, left, left, left),
      header: ([Decision], [Value], [Recorded by], [Reason given]),
      rows: decs.map(dd => (
        raw(dd.key), str(dd.value),
        if dd.at("authored_by_agent", default: false) { "the agent" } else { dd.decided_by },
        dd.reason)), size: 7.5pt),
    caption: [Decisions Recorded for This Assessment],
  )
]

#if auth.at("by_agent", default: 0) > 0 [
  #callout("Decisions Taken by the Agent")[
    #str(auth.by_agent) of the #str(auth.by_agent + auth.by_person) judgements above
    were taken by the analysis agent because no position had been recorded for
    them, and are attributed to it in the table. They are
    #auth.agent_authored_keys.map(k => raw(k)).join(", "). Findings that depend on
    them are conditional on a machine's assumption rather than a district
    position, and should be read accordingly.
  ]
] else [
  Every judgement above was recorded by a person before the analysis ran.
]

== Data Sources

#let srcrows = d.provenance.map(p => (p.source, p.endpoint, p.licence, p.fetched_at.slice(0, 10)))
#figure(
  gov-tbl(
    columns: (auto, 1fr, auto, auto),
    align: (left, left, left, right),
    header: ([Source], [Endpoint], [Licence], [Retrieved]),
    rows: srcrows, size: 8pt),
  caption: [Sources Used in this Assessment],
)

// ============================================================ ch 2
= Chapter 2: Situation Overview

Chapter 2 describes service coverage in #scope.adm2 District as recorded at the
time of retrieval, and states the size of the population that a capital
programme in this district would be seeking to reach.

== Recorded Service Coverage

An estimated #thousands(base.population) people live within the area of
interest. #thousands(base.covered) of them, #pct(base.covered_share), live
#scope.coverage_rule of a #scope.unit recorded as serving. The remaining
#thousands(base.uncovered) people, #pct(1 - base.covered_share) of the district,
do not.

The register holds #thousands(scope.points_total) #scope.unit records for this
district after cleaning. #thousands(scope.points_working) are recorded as
serving and #thousands(scope.points_broken) are not, which is
#pct(scope.points_broken / scope.points_total, digits: 0) of the recorded stock.

#figure(
  gov-tbl(
    columns: (1fr, auto, auto),
    align: (left, right, right),
    header: ([Category], [People], [Share of district]),
    rows: (
      ("Within the service radius of a serving " + scope.unit,
       thousands(base.covered), pct(base.covered_share)),
      ("Beyond the service radius", thousands(base.uncovered), pct(1 - base.covered_share)),
      ("Total resident population", thousands(base.population), "100.0%"),
    )),
  caption: [Recorded Coverage Before Intervention],
)

#figure(
  image("map_situation.png", height: 100mm),
  caption: [Recorded #titlecase(scope.unit)#if scope.budget > 1 [s] and Population Beyond the Service Radius],
)

#source-line[
  Sources: #d.provenance.map(p => p.source).join("; "). Coordinates WGS 84.
  Warm shading indicates population beyond the service radius of any
  #scope.unit recorded as serving.
]

== The Gap Expressed in People

A percentage conceals the size of the problem. #thousands(base.uncovered) people
is the figure that bears on planning: it is the population a capital programme in
this district would be attempting to reach.

// ============================================================ ch 3
= Chapter 3: Assessment Methodology

Chapter 3 states how the assessment was carried out. It covers retrieval and
cleaning, the construction of the demand surface and the candidate set, the
selection method and the guarantee it carries, and the validation applied before
findings were released.

== Retrieval and Cleaning

Each source is governed by a handbook file that declares its endpoint, the
meaning of its fields, and the cleaning rules to be applied in order. Each rule
reports its own drop count, so no record leaves the pipeline unaccounted for.

#let cleanrows = d.provenance.map(p => (
  p.source, thousands(p.rows_raw), thousands(p.rows_clean), thousands(p.dropped_total)))
#figure(
  gov-tbl(
    columns: (1fr, auto, auto, auto),
    align: (left, right, right, right),
    header: ([Source], [Returned], [Retained], [Discarded]),
    rows: cleanrows),
  caption: [Records Retrieved and Retained],
)

#let wp = d.provenance.find(p => p.dropped_total > 0)
#if wp != none [
  Records were discarded from #wp.source for the following reasons:
  #wp.drops.pairs().map(((r, n)) => thousands(n) + " " + r).join("; ").

  #callout("Why Discarded Records Are Itemised")[
    A register that returns a record does not necessarily hold a distinct, current
    observation. Where a source ships duplicate rows and superseded observations in
    the same response, coverage computed on the raw response counts settlements
    twice and treats retired observations as current. Every rule that removes a
    record is declared in advance and reports how many it removed, so the
    difference between the returned and retained counts above is fully explained.
  ]
]

== Coordinate Reference System

All distance, radius and separation computations are carried out in
#scope.crs. #scope.crs_rationale

Over #str(scope.crs_check.pairs) sampled pairs of demand cells, projected
distance departs from great-circle distance by
#pct(scope.crs_check.median_relative_error, digits: 3) at the median and
#pct(scope.crs_check.max_relative_error, digits: 3) at most, which on a
#str(calc.round(scope.radius_m)) m service radius is about
#str(calc.round(scope.crs_check.max_relative_error * scope.radius_m)) m.

#callout("Why Distance Is Not Computed in Degrees")[
  Computing distance directly from latitude and longitude is among the most
  common errors in applied spatial analysis, because a degree of longitude is
  not a fixed ground distance and shrinks towards the poles. A service radius is
  precisely the kind of claim that must hold in metres on the ground, so the
  analysis projects first and measures second. The figures above state how far
  the chosen projection departs from the sphere here, rather than assuming the
  difference away.
]

== Demand Surface

Population is taken from a gridded estimate at approximately 100 m resolution,
read over the area of interest and aggregated into blocks coarser than the source
and finer than the service radius, so that aggregation does not bias coverage.
#thousands(base.demand_cells) demand cells result, together holding
#thousands(base.population) people.

== Candidate Set

#thousands(base.candidates) candidate locations were evaluated. Two kinds were
admitted: an existing #scope.unit recorded as not serving, which could be
rehabilitated, and a regular lattice of new locations at
#str(calc.round(scope.grid_m)) m spacing. Lattice points already inside an
existing service area were removed before selection. Recommendations are
constrained to lie at least #str(calc.round(scope.min_separation_m)) m apart.

== Selection Method

#plan.at("method", default: "The selection method was not recorded for this run.")

#plan.at("guarantee", default: "")

#callout("Coverage Is a Union, Not a Sum")[
  A settlement within reach of two #scope.unit#if scope.budget > 1 [s] is served
  once, not twice. Coverage throughout this assessment is therefore the union
  over selected locations. Summing the population served by each location
  separately overstates coverage, and the independent recount reported at
  Section 5.2 states by how much it would have done so here.
]

== Validation

Before findings were released, the plan was checked by a separate process that
can reject it but cannot amend it, and which does not read the reasons recorded
in Chapter 5. A single rejection stops the assessment being issued. The results
of those checks are at Section 5.2.

// ============================================================ ch 4
= Chapter 4: Findings

Chapter 4 gives the recommended placements, the population each would reach, and
the basis on which each was selected.

== Recommended Placements

#figure(
  gov-tbl(
    columns: (auto, auto, auto, auto, auto, auto),
    align: (right, left, left, left, right, right),
    header: ([No.], [Site], [Type], [Location (WGS 84)], [Newly covered], [Nearest serving]),
    rows: plan.sites.map(s => (
      str(s.rank), s.id, s.kind,
      coord(s.lat, s.lon),
      thousands(s.newly_covered),
      if s.nearest_working_m == none { sym.dash.em } else { km1(s.nearest_working_m) },
    )), size: 8pt),
  caption: [Recommended #titlecase(scope.unit) Placements, in Selection Order],
)

Each row's coverage is additional to every row above it. The programme must
therefore be built from the top of the table down; taking rows out of order does
not produce the stated coverage.

#figure(
  image("map_plan.png", height: 100mm),
  caption: [Recommended Placements and Their Service Radii],
)

== Coverage Achieved

Selecting the #str(plan.sites.len()) placements above brings a further
#thousands(plan.newly_covered) people inside the service radius, raising recorded
coverage from #pct(base.covered_share) to #pct(plan.covered_share).

#figure(
  gov-tbl(
    columns: (auto, auto, auto, auto),
    align: (right, right, right, right),
    header: ([Placements built], [Newly covered], [Cumulative covered], [Share of district]),
    rows: curve.map(c => (
      str(c.n), thousands(c.marginal), thousands(c.cumulative), pct(c.cumulative_share)))),
  caption: [Marginal and Cumulative Coverage by Number of Placements],
)

#callout("Determining How Many to Build")[
  Returns fall away as placements are added. The first placement reaches
  #thousands(curve.at(0).marginal) people; the
  #str(curve.len())#super[th] reaches #thousands(curve.last().marginal). A budget
  decision taken against Table 5 rather than against a round number will reach
  more people for the same expenditure.
]

== Basis for Each Placement

#for s in plan.sites [
  #grid(columns: (46pt, 1fr), column-gutter: 8pt,
    text(font: sans-bold, size: 9pt, weight: 700)[#s.id],
    text(font: sans, size: 9pt)[#s.rationale])
  #v(3pt)
]

// ============================================================ ch 5
= Chapter 5: Review and Determination

Chapter 5 records the review of the findings in Chapter 4: where a reviewing
officer overruled the analysis, what each such decision cost in coverage, and the
outcome of the checks applied independently of the analysis.

== Reviewing Officer Determinations

#if d.audit.len() > 0 [
  Each determination below was applied on its own and the plan re-solved, so that
  each carries its own cost rather than one aggregate figure. No determination
  was blocked. A determination excluding a location excludes an area around it,
  not a single lattice point.

  #figure(
    gov-tbl(
      columns: (auto, auto, 1fr, auto),
      align: (left, left, left, right),
      header: ([Determination], [Site], [Reason recorded], [Coverage cost]),
      rows: d.audit.map(a => (
        a.verb, a.target, a.reason,
        (if a.delta_covered > 0 { "+" } else { "" }) + thousands(a.delta_covered))),
      size: 8pt),
    caption: [Reviewing Officer Determinations],
  )

  #callout("Effect of Determinations on Coverage")[
    #d.guardrail.verdict
  ]
] else [
  No reviewing officer determinations were recorded. The findings at Chapter 4
  are the unmodified output of the method at Chapter 3.
]

== Independent Checks

#figure(
  gov-tbl(
    columns: (auto, auto, 1fr),
    align: (left, center, left),
    header: ([Check], [Result], [Finding]),
    rows: d.evaluation.map(f => (f.check, level-mark(f.level), f.detail)), size: 8pt),
  caption: [Checks Applied Before Issue],
)

#let flags = d.evaluation.filter(f => f.level == "flag")
#if flags.len() > 0 [
  #flags.len() of the #d.evaluation.len() checks returned a flag rather than a
  pass. A flag does not prevent issue, and the finding is reproduced above in the
  terms in which it was raised. It is not resolved in this assessment.
] else [
  All #d.evaluation.len() checks returned a pass.
]

== Scoring Review

#let rv = d.at("review", default: none)
#if rv != none [
  Before issue, the account of this assessment was scored by a reviewer that
  receives the results file and nothing else: not the solver, not the code path,
  and not the reasons recorded in Section 5.1. It scores the account given, not
  the intention behind the plan.

  #figure(
    gov-tbl(
      columns: (1fr, auto, auto, auto, auto),
      align: (left, right, right, right, left),
      header: ([Dimension], [Score], [Floor], [Weight], [Outcome]),
      rows: rv.scores.map(s => (
        s.dimension, fixed(s.value, 1), fixed(s.floor, 1), fixed(s.weight, 2),
        if s.passes { "met" } else { "below floor" })), size: 8pt),
    caption: [Review Scores Against Their Floors],
  )

  The weighted score is #fixed(rv.weighted, 2) against a floor of
  #fixed(rv.accept_at, 2). The assessment is issued only when the weighted score
  and every individual floor are met. Reviewer: #rv.reviewer.

  #if rv.at("forced", default: false) [
    #callout("Issued Below the Review Floor")[
      This assessment scored below the floor and was issued on an explicit
      instruction rather than because the floor was met. The outstanding items are
      listed below and are not resolved here.
    ]
  ]

  #if rv.action_items.len() > 0 [
    Outstanding items recorded by the reviewer:
    #for a in rv.action_items [
      - #a
    ]
  ]
]

#let gates = d.at("gate_decisions", default: ())
#if gates.len() > 0 [
  == Gate Decisions

  A gate never silently permits. Each row below is a point at which the run
  either proceeded and recorded why that was safe, or refused. A refusal removes
  a source from the analysis and is stated here rather than left to be inferred
  from a missing figure.

  #figure(
    gov-tbl(
      columns: (auto, auto, auto, 1fr),
      align: (left, left, left, left),
      header: ([Gate], [Outcome], [Decided by], [Reason recorded]),
      rows: gates.map(g => (
        g.checkpoint, if g.allowed { "allowed" } else { "refused" },
        g.actor, g.reason)), size: 7.5pt),
    caption: [Safety Gate Decisions],
  )
]

// ============================================================ ch 6
= Chapter 6: Sensitivity

Chapter 6 tests how far the recommendation at Chapter 4 depends on assumptions
that a reviewing officer may reasonably wish to change. Each scenario re-solves
from the same retrieved data with a single assumption altered.

#if d.sensitivity.len() > 0 [
  #figure(
    gov-tbl(
      columns: (1fr, auto, auto, auto),
      align: (left, right, right, right),
      header: ([Scenario], [Covered], [Share], [Against base case]),
      rows: d.sensitivity.map(s => (
        s.label, thousands(s.covered), pct(s.share),
        (if s.delta > 0 { "+" } else { "" }) + thousands(s.delta) + " people"))),
    caption: [Sensitivity of the Recommendation],
  )

  #callout("Rehabilitation Against New Construction")[
    The base case does not select rehabilitation of existing
    #scope.unit#if scope.budget > 1 [s], because a location recorded as not
    serving generally stands beside one that is serving and therefore adds little
    new coverage. Rehabilitation is nonetheless materially cheaper per unit than
    new construction, and cost is not modelled in this assessment. Table 8 states
    what a rehabilitation-only programme of the same size would achieve, so the
    two can be weighed against costs held by the district.
  ]
] else [
  No sensitivity scenarios were run for this assessment.
]

// ============================================================ appendices
= Appendix A: Data Anomalies and Their Handling

Each item below is a property of the published source data that would have
changed a figure in this assessment had it been read differently. Each is
recorded with what was observed, what was done, and what a reader must hold in
mind as a result. None were resolved silently.

#if d.anomalies.len() > 0 [
  #for (i, a) in d.anomalies.enumerate() [
    #v(6pt)
    #text(font: sans-bold, size: 10pt, weight: 700, fill: navy)[
      A.#str(i + 1) #upper(a.kind) #sym.dot.c #a.source
    ]
    #v(3pt)
    #table(
      columns: (72pt, 1fr),
      stroke: none,
      inset: (x: 0pt, y: 3pt),
      text(font: sans-bold, size: 8.5pt, weight: 700)[Observed],
      text(font: sans, size: 9pt)[#a.observed],
      text(font: sans-bold, size: 8.5pt, weight: 700)[Handling],
      text(font: sans, size: 9pt)[#a.handling],
      text(font: sans-bold, size: 8.5pt, weight: 700)[Bearing],
      text(font: sans, size: 9pt)[#a.consequence],
    )
  ]
] else [
  No anomalies were recorded for this assessment.
]

= Appendix B: Retrieval Record

Every retrieval made for this assessment, with the query as executed.

#for p in d.provenance [
  #v(6pt)
  #text(font: sans-bold, size: 10pt, weight: 700, fill: navy)[#p.source]
  #v(3pt)
  #verbatim(p.query)
  #v(3pt)
  #let cachenote = if p.at("from_cache", default: false) [, and read from this machine's local cache for the present run rather than requested again] else []
  #source-line[
    Endpoint #p.endpoint. Retrieved #p.fetched_at#cachenote. Returned
    #thousands(p.rows_raw) records, retained #thousands(p.rows_clean).
    Licence: #p.licence.
  ]
  #v(4pt)
]

= Appendix C: Reproduction Record

This assessment is a function of one results file and the manifest that produced
it. Replaying the command below against the recorded queries regenerates it.

#verbatim(d.command, lang: "sh")

#v(6pt)
Provenance hash #raw(d.run.provenance_hash). Any change to a source query, a
cleaning rule or a retrieval date changes this hash.

#if d.overrides_source != "" [
  #v(10pt)
  #text(font: sans-bold, size: 11pt, weight: 700)[Determinations file as supplied]
  #v(4pt)
  #verbatim(d.overrides_source, lang: "yaml")
]

#v(10pt)
#figure(
  gov-tbl(
    columns: (1fr, auto, auto),
    align: (left, left, right),
    header: ([Source], [Licence], [Accessed]),
    rows: d.references.map(r => (r.citation, r.licence, r.accessed)), size: 8pt),
  caption: [Sources, Licences and Access Dates],
)
